image: openjdk:8
tasks:
  - init: source ./gitpod_init.sh
  - command: source ./gitpod_command.sh
vscode:
  extensions:
    - scalameta.metals@1.8.0:COLt/susY54OcSJMqJKofQ==
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - k--kato.intellij-idea-keybindings@0.2.37:vz3hpwf8WGtALEI7zq/EXA==